import "../resources/styles/globals.scss";
import "../resources/styles/fira_code_normal.scss";
import "../resources/styles/fira_code_mono.scss";
import "../resources/styles/fira_code_propo.scss";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
